### ISSUE TITLE
Kotlin 1.5.30 - ClassNotFoundException: org.jetbrains.kotlin.konan.target.HostManager

### ISSUE THREAD

**Issue by joffrey-bion** [LouisCAD/CompleteKotlin#7] opened 2021-09-02 08:09 UTC
I noticed some strange behaviour on my local Windows 10 machine, which I [don't reproduce in Github Actions](https://github.com/joffrey-bion/krossbow/actions/runs/1192053733) (neither ubuntu, nor windows, nor macos runners).

When I try to upgrade the Kotlin gradle plugins to 1.5.30, I get the following error on every Gradle run no matter the task executed (`./gradlew clean`, `./gradlew build`, even `gradle wrapper`) - so it's probably a configuration phase issue:

```
An exception occurred applying plugin request [id: 'org.jetbrains.kotlin.multiplatform']
> Failed to apply plugin 'org.jetbrains.kotlin.multiplatform'.
   > org.jetbrains.kotlin.konan.target.HostManager
```

This is a hint at the actual stacktrace (more complete stack in the expand at the bottom):
```
Caused by: java.lang.ClassNotFoundException: org.jetbrains.kotlin.konan.target.HostManager
        at com.louiscad.complete_kotlin.internal.HostPlatform$Companion$platformName$2.invoke(HostPlatform.kt:20)
```

Here is a build scan for more details: https://scans.gradle.com/s/z3ry63v3gtq4u

If I comment out the complete-kotlin plugin in `settings.gradle.kts`, the error is gone. This is extremely consistent behaviour, I just never managed to make Kotlin 1.5.30 and Complete Kotlin plugin work at the same time locally.

I am using:

* Gradle 7.2
* JDK 15.0.1 (Oracle Corporation 15.0.1+9-18)
* Windows 10 10.0 Amd64
* IDEA Kotlin plugin 212-1.5.30-release-409-IJ4638.7 (although it shouldn't matter since I reproduce in command line)
* My project only uses `ios()` among the native targets (but also uses JVM and JS - browser and node)

On the CI, it does seem to work fine though, which makes me think it's either some misconfiguration on my machine, or architecture/platform specific issue that happens on Windows desktop, but not on Windows server. I could also reproduce with a basic multiplatform project generated by IDEA, to which I simply added `jvm()` and `ios()` targets, and the complete kotlin plugin.

Any idea how I could investigate this further?

<details>
    <summary>Actual stacktrace (but trimmed) with `--stacktrace`</summary>

```
org.gradle.api.plugins.InvalidPluginException: An exception occurred applying plugin request [id: 'org.jetbrains.kotlin.multiplatform']
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.exceptionOccurred(DefaultPluginRequestApplicator.java:207)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugin(DefaultPluginRequestApplicator.java:189)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.lambda$applyPlugins$1(DefaultPluginRequestApplicator.java:127)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugins(DefaultPluginRequestApplicator.java:127)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugins(DefaultPluginRequestApplicator.java:123)
        at org.gradle.kotlin.dsl.provider.PluginRequestsHandler.handle(PluginRequestsHandler.kt:48)
        at org.gradle.kotlin.dsl.provider.StandardKotlinScriptEvaluator$InterpreterHost.applyPluginsTo(KotlinScriptEvaluator.kt:193)
        at org.gradle.kotlin.dsl.execution.Interpreter$ProgramHost.applyPluginsTo(Interpreter.kt:394)
        at Program.execute(Unknown Source)
    ....(I cut a bunch of gradle internals here)
Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin 'org.jetbrains.kotlin.multiplatform'.
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:173)
        at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:137)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.lambda$applyPlugins$0(DefaultPluginRequestApplicator.java:129)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugin(DefaultPluginRequestApplicator.java:185)
        ... 156 more (cut by IDEA)

Caused by: org.gradle.internal.operations.BuildOperationInvocationException: org.jetbrains.kotlin.konan.target.HostManager
        at org.gradle.internal.operations.DefaultBuildOperationRunner.throwAsBuildOperationInvocationException(DefaultBuildOperationRunner.java:188)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.access$100(DefaultBuildOperationRunner.java:24)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:84)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
        ... (cut by me)
Caused by: java.lang.ClassNotFoundException: org.jetbrains.kotlin.konan.target.HostManager
        at com.louiscad.complete_kotlin.internal.HostPlatform$Companion$platformName$2.invoke(HostPlatform.kt:20)
        at com.louiscad.complete_kotlin.internal.HostPlatform$Companion$platformName$2.invoke(HostPlatform.kt:18)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.louiscad.complete_kotlin.internal.HostPlatform$Companion.getPlatformName(HostPlatform.kt)
        at com.louiscad.complete_kotlin.internal.KotlinNativeCompilerInfo.<init>(KotlinNativeCompilerInfo.kt:21)
        at com.louiscad.complete_kotlin.internal.KotlinNativeCompilerDirs.<init>(KotlinNativeCompilerDirs.kt:10)
        at com.louiscad.complete_kotlin.internal.TargetsHandlerKt.completePlatformKlibsIfNeeded(TargetsHandler.kt:26)
        at com.louiscad.complete_kotlin.CompleteKotlinPlugin$setup$1$1$1.execute(CompleteKotlinPlugin.kt:48)
        at com.louiscad.complete_kotlin.CompleteKotlinPlugin$setup$1$1$1.execute(CompleteKotlinPlugin.kt:16)
        at org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication$1.execute(DefaultUserCodeApplicationContext.java:123)
        at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1.run(DefaultCollectionCallbackActionDecorator.java:110)
        ... (cut by me)
```
</details>

**Comment by joffrey-bion** [comment] 2021-09-02 08:24
It does seem that this line relies on the `HostManager` class being present on the classpath:
https://github.com/LouisCAD/CompleteKotlin/blob/main/plugin/src/main/kotlin/com/louiscad/complete_kotlin/internal/HostPlatform.kt#L20

But I'm not sure what it means that the class is absent on my Windows 10 local machine, but present on the CI. It could be due to the Gradle cache from the CI, but I wonder why old Kotlin classes would be loaded there but not on my machine.

I also tried removing the only difference between local and CI gradle config: Gradle enterprise's build scan tags configuration (why might have loaded more stuff from Kotlin's 1.5.21's classes). It [still builds fine on the CI](https://github.com/joffrey-bion/krossbow/runs/3493453764).

**Comment by LouisCAD** [comment] 2021-09-02 09:16
CompleteKotlin doesn't run on CI because it's not needed there:
https://github.com/LouisCAD/CompleteKotlin/blob/f5bd9296b91b2e08e9ef964308f5241daab6da22/plugin/src/main/kotlin/com/louiscad/complete_kotlin/CompleteKotlinPlugin.kt#L33-L37

I'll check what's happening on a project.

**Comment by joffrey-bion** [comment] 2021-09-02 09:20
> CompleteKotlin doesn't run on CI because it's not needed there

Well that clarifies a bunch of my doubts, sorry I didn't think of that.

Thanks a lot for checking this out. You can create a reproducer using IDEA's project wizard (I used Gradle Kotlin DSL + Kotlin Multiplatform project, added `jvm()` and `ios()` targets, and the CompleteKotlin plugin 1.0.0).

Please let me know if I can do anything to help

**Comment by joffrey-bion** [comment] 2021-09-11 00:29
Did you have a chance to look at this?

For the record, it seems the `HostManager` is still there in Kotlin 1.5.30:
https://github.com/JetBrains/kotlin/blob/1.5.30/native/utils/src/org/jetbrains/kotlin/konan/target/HostManager.kt

Could it be a classpath issue then?

**Comment by LouisCAD** [comment] 2021-09-11 01:01
Yes, it looks like it's a classpath issue that happens since 1.5.30 and I'm not sure why nor how to work around it.

I'm suspecting the Kotlin daemon and Java toolchain support is involved in the issue, but I have no clue about what I can do. If you have any idea, please let me know.

Otherwise, I'll try to get someone from JetBrains to help me figure it out once they have released Kotlin 1.6-M1.

**Comment by joffrey-bion** [comment] 2021-09-13 12:54
I discussed with a colleague at JetBrains, it seems that it works if we declare a Kotlin plugin dependency in the `plugins` block in the settings file:

`settings.gradle.kts`:
```kotlin
plugins {
    id("com.gradle.enterprise") version "3.2.1"
    id("com.louiscad.complete-kotlin") version "1.0.0"
    id("org.jetbrains.kotlin.jvm") version "1.5.30" apply false // adds required deps on the classpath
}
```

Which also requires removing the Kotlin version on Kotlin plugins in `build.gradle.kts` to avoid the error:

>  Plugin request for plugin already on the classpath must not include a version

Could you please explain a little why this plugin needs to be applied on the `settings.gradle(.kts)` file and not on `build.gradle(.kts)`? (sorry for my ignorance here)

**Comment by joffrey-bion** [comment] 2021-09-13 21:51
Ok, more info about what is wrong and why we observe this behaviour (compliments of Ilya Matveev): the CompleteKotlin plugin simply doesn't reach this `HostManager` instantiation before 1.5.30, but it would fail just the same in 1.5.21 if we tried.

In fact, the plugin only accesses it when `compilerVersion.supportsPlatformName()` is true, which only happens since `1.5.30-dev-1466`:
https://github.com/LouisCAD/CompleteKotlin/blob/099b3a044ac4594729ef51cffd3b3b66313d4485/plugin/src/main/kotlin/com/louiscad/complete_kotlin/internal/CompilerVersion.kt#L66-L75

It seems CopmleteKotlin is already aware of a change in naming scheme in native distributions since 1.5.30, so that is fine, but we still have this dependency problem because `HostManager` is not present unless a `kotlin-compiler-embeddable.jar` is on the classpath. So it works when we add a Kotlin Gradle plugin on the classpath, but this feels wrong.

It looks like moving the plugin from a settings plugin to a project plugin would solve the problem as well, hence my question why is it a settings plugin in the first place?
If it really has to be, then maybe it could be useful to add a dependency on `kotlin-compiler-embeddable` 🤔

**Comment by LouisCAD** [comment] 2021-09-13 22:30
I made it a settings plugin because that'd bring no ambiguity as to which file to put it in, but it looks like I'll change that.

I'll try to spend some time on it this week and make a new release.

**Comment by LouisCAD** [comment] 2021-09-13 22:31
Thanks a lot for your investigation BTW, it's very helpful!

**Comment by joffrey-bion** [comment] 2021-09-13 22:37
> I'll try to spend some time on it this week and make a new release.

Thanks a lot for that!

> Thanks a lot for your investigation BTW, it's very helpful!

Happy to help, but to be fair I mostly asked for help myself. The people to really thank are @Tapchicoma and @IlMatveev 😉

**Comment by joffrey-bion** [comment] 2021-12-26 22:36
Any news on this?

**Comment by LouisCAD** [comment] 2022-01-09 15:37
That's related to #9, I need to update the plugin for newer Kotlin versions.

Here's a quote of [my answer](https://github.com/LouisCAD/CompleteKotlin/issues/9#issuecomment-1008320369) for reference:

> Hello, sorry for the radio silence, I was a bit busy and lacked the feeling of breathing room to focus on that deeply.
> 
> I'll try to update the plugin for new Kotlin versions this afternoon, but I might not be done today, we'll see.
> 
> If you want to help, we can pair-program together, you can reach me on Kotlin Slack or via Twitter DM.

**Comment by LouisCAD** [comment] 2022-01-10 20:27
Should be fixed in 1.1.0.

If it still reproduces, **please let me know**, then remove the plugin from `settings.gradle[.kts]` and put it in the root `build.gradle[.kts]` file, as now documented in the README since version 1.1.0.

**Closed by LouisCAD** 2022-01-10 20:27 UTC

**Comment by joffrey-bion** [comment] 2022-01-10 23:04
It sill reproduces in 1.1.0 when applying the plugin from `settings.gradle.kts` without the workaround mentioned above (adding `"org.jetbrains.kotlin.jvm"` plugin in `settings.gradle.kts` too with `apply false`) - which I guess is to be expected.

It's solved when applying version 1.1.0 in `build.gradle.kts`. Thanks a lot!

**Comment by LouisCAD** [comment] 2022-01-11 00:05
Thanks for confirming, I had the same behavior on the sample project.

I'll add an error message for when the plugin is applied from settings in 1.1.1, and I'll be more careful with settings Gradle plugins from now on.

**Comment by LouisCAD** [comment] 2022-01-11 00:06
@sigurdurrafn @johnameyer ☝️
